### ISSUE TITLE
[Feat] NI, MPC UI에 연결

### ISSUE THREAD

**Issue by kpk0616** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#20]
## 🛠 Issue

- 내 주변 버디를 확인하고 운동 데이터를 공유하기 위해 Nearby Interaction, Multipeer Connectivity를 사용한다.
- 나의 운동 정보를 HealthKit에서 가져와야 한다.
- 자잘한 컴포넌트 UI 수정, 뷰 간 연결을 한다.

## 📝 To-do

- [ ] 파트너 찾기 → Modal, Alert띄우기 (Nearby Interaction)
- [ ] 운동중, 유저 운동 완료 → 모달 띄우기 (HealthKit, CoreData)
- [x] 운동이 덜 끝났을 때 팝업되는 모달 UI 수정, 다른 뷰와 연결
- [ ]
