### ISSUE TITLE
[Feat] Search Partner View에 로딩 애니메이션 추가

### ISSUE THREAD

**Issue by jay1261** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#34]
## 🛠 Issue

파트너 검색 중에 로딩 애니메이션 추가 작업 이슈

## 📝 To-do

- [ ] 로딩 애니메이션 추가
- [ ] 안녕 버튼 삭제
- [ ] 연결 완료시 원 3개화면 추가
