### ISSUE TITLE
[Feat] User Data Save

### ISSUE THREAD

**Issue by bokoo14** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#36]
## 🛠 Issue

운동 중이라는 것을 user default에 저장
메인뷰에 있는 버튼을 바꿔야 함
사용자가 갖고 있는 토큰을 계속 연결중인 상태로 만들어줘야 함(앱을 꼈다 켰을때 - 연결이 지속되어 있어야 함)

## 📝 To-do

- [x] Workout View로 넘어갈때 사용자가 운동 중이라는 것을 user default에 저장
- [x] 사용자가 운동 중이라면 Main View에 있는 버튼을 바꿔야 함
- [ ] 운동 종료 시 내 기록 Coredata 저장 - settings.istodayworkout (userdefault)값 변경, 운동 기록 Coredata에 저장
- [x] 상대방과 통신 후 상대방의 uuid, 운동 완료 여부 user default에 저장
- [x] SearchPartner View에서 연결하기 버튼을 누른 후 애플워치 착용까지 확인하면 -> 사용자와 연결했던 피어가 운동종료 후 커넥트한 피어와 일치하는지 확인하기 - 코어데이터 내에 UUID를 생성 후 저장)
- [x] WorkoutView에서 그만할래요를 누르면 다음뷰로 넘어가지 않는 Error
