### ISSUE TITLE
[Feat] 운동 완료 화면 모달, 백버튼 모션 구현 완료

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#39]
## 🛠 Issue
운동 완료 버튼을 누를 때, 목표 미달성시 모달이 뜨는 것
그리고 '수고하셨어요' 화면에서 버튼을 누르면 메인화면으로 가는 것,
운동하기 화면에 전체 화면 레이아웃을 수정합니다.
진화 화면도 일부 수정하여 연결하겠습니다.

## 📝 To-do
- [x] 운동 완료 버튼 누를 때 목표 미달성 모달 구현
- [x] 목표 달성 확인 버튼 누를 때 목표 미달성 모달 구현
- [x] 수고하셨어요 화면에서 버튼을 누르면 메인화면으로 가는 것
- [x] 운동하기 플로우에 있는 화면(네비게이션히든 한 것) 레이아웃(패딩 값) 수정
- [x] 진화화면 일부 수정, 마지막 버튼에서 연결
