### ISSUE TITLE
[Feat] Mian View 수정

### ISSUE THREAD

**Issue by Hanyeonggyun** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#47]
## 🛠 Issue

메인 뷰 작업을 마무리 합니다.

## 📝 To-do

- [x] 다음 성장까지 남은 운동 횟수 표시
- [x] 레벨 변화에 따른 이미지 가져오기
- [x] 오늘의 운동 시간, 소모 칼로리 나타내기
