### ISSUE TITLE
[Feat] 진화뷰, 파트너뷰 마무리 수정

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#48]
## 🛠 Issue
현재 미완성된 뷰의 부분들을 완성시킵니다. 이 이슈가 끝나면 캐릭터 삽입 태스크만 남게 됩니다.

## 📝 To-do

- [x] 세팅뷰 - 칼로리 설정시 본인이 설정한 칼로리로 처음 값이 나타나도록 변경
- [x] 칼로리 재 세팅시 상단 뒤로가기 버튼 숨기기
- [x] 진화 뷰의 목표달성 변수 조정
- [x] SearchPartnerView 파트너 발견시 이미지 수정, 텍스트 수정, 버튼 '연결하기'에서 다른 것으로 바꾸기
