### ISSUE TITLE
Issue #5

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#5]
## 🛠 Issue
Feature/#2에 대한 Issue입니다.
5월 4일 추가 논의 후 필요 뷰 확정에 따른 추가 뷰 작업입니다.
필요한 뷰 파일을 생성하고, 내부 컴포넌트를 배치하는 작업을 합니다.
UserDefalut를 활용한 데이터 저장 작업과 그에 따른 뷰 연결 작업은 다음 Feature 작업에서 진행합니다.

## 📝 To-do
- [x] 목표 칼로리 설정 뷰 분할
- [x] 온보딩 페이지 생성
- [x] 온보딩 페이지 연결 완료
- [x] 발견된 파트너가 없어요 모달 생성
- [x] 파트너가 운동 중일 때 뜨는 모달 생성
- [x] 하루 목표치를 채우지 못했다는 모달 생성
- [x] 목표 달성화면, 미달성 화면 생성
- [x] 진화화면 생성
- [x] 내정보 화면 생성
- [x] 진화 트리 화면 생성
