### ISSUE TITLE
[Feat] 레벨에 따른 캐릭터 및 진화 로드맵 이미지 변화 + 깨지는 이미지  2x, 3x 추가

### ISSUE THREAD

**Issue by Hanyeonggyun** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#55]
## 🛠 Issue

 레벨에 따른 캐릭터 및 진화 로드맵 이미지 변화 + 깨지는 이미지  2x, 3x 추가
## 📝 To-do

- [ ] 레벨 변화에 따른 메인 뷰 캐릭터 변화
- [ ] 레벨 변화에 따른 진화 로드맵 이미지 변화
- [ ] 깨지는 이미지 2x, 3x 추가
