### ISSUE TITLE
[Hotfix] 디버깅 오류

### ISSUE THREAD

**Issue by bokoo14** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#59]
## 🛠 Issue

실 기기에서 테스트하는 동안 디버깅 오류가 발생하였습니다

## 📝 To-do

- [ ] 운동 데이터 제대로 불러오지 못해 모달이 뜸
- [ ] 접촉하기 버튼을 눌렸는지 잘 모름
- [ ] 운동 끝나고 니오는 연결 잘 안됨 -> 두번 누를때 문제가 있음, 안정성 문제 (한번만 누르면 잘됨, 2번이상 누르면 bumped가 안됨)
- [ ] 최종화면 나오고 운동 상태 종료가 안될 때가 있다. 메인 뷰로 갈때 운동이 끝났음에도 운동하기 화면으로 감
