### ISSUE TITLE
[Feat] 캐릭터 이름, 닉네임 재설정 기능 추가

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#67]
## 🛠 Issue

캐릭터 이름, 사람 이름 Update 가능하도록 변경

## 📝 To-do

- [ ] SettingView 상단 사람 이름, 캐릭터 이름있는 섹션 디자인 변경
- [ ] 닉네임 변경 뷰, 데이터 업데이트 로직 변경
- [ ] 캐릭터 이름 변경 뷰, 데이터 업데이트 로직 변경
