### ISSUE TITLE
[Fix] 운동종료 후 NI 한 뒤 모달뷰가 제대로 뜨지 않는 문제 해결

### ISSUE THREAD

**Issue by kpk0616** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#76]
## 🛠 Issue

운동 종료 후, 파트너와 연결해 데이터를 교환한 뒤 **파트너의 목표달성 여부를 확인하고 모달 / 내비게이션뷰를 띄우는 로직**을 구현해놓았는데 이 로직이 제대로 동작하지 않고 있습니다.
데이터 통신이 이뤄지는 부분에서 오류가 나는건지, 모달을 띄우는 로직에서 오류가 나는건지 불확실합니다.

## 📝 To-do

- [ ] 오류 파악 - 파트너가 운동을 완료하지 않았을때는 "파트너가 아직 운동 중이에요" 정상 작동, 파트너가 목표 달성을 했을때도 "파트너가 아직 운동 중이에요" 모달이 띄워짐  
- [ ] 오류: NISession에서 데이터를 Tran할때 내가 목표를 달성했는지 여부를 주고받지 않았음, 나와 상대방 모두가 운동을 완료했는지를 check하는 로직이 잘못됨
- [ ] 오류 해결: NISessionManager의 데이터 통신, settings.isDoneTogetherWorkout변수 로직 해결
