### ISSUE TITLE
[Refactor] CoreData 싱글턴 패턴 활용 구조로 변경

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#91]
## 🛠 Issue

settings를 걷어내고, CoreDataManager를 일부 수정한 다음,
CoreData를 싱글턴 패턴으로 활용하는 구조로 변경합니다.

이와 관련된 View의 변수들도 변경합니다.

## 📝 To-do

- [x] CoreDataManager CRUD 메서드 수정
- [x] CoreData UserData DataModel 프로퍼티, 메서드 추가
- [x] CoreData WorkoutData DataModel 프로퍼티, 메서드 추가
- [x] CoreData CharacterData DataModel 프로퍼티, 메서드 추가
