### ISSUE TITLE
[Feat] 1인 기능 개발

### ISSUE THREAD

**Issue by bokoo14** [DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy#95]
## 🛠 Issue

버닝버디의 새로운 기능인 1인 기능입니다. 
유저가 혼자서도 앱을 사용하여 버디를 키울 수 있도록 합니다. 

## 📝 To-do

- [x] 메인 페이지에서 1인기능, 2인 기능 선택하기 뷰
- [x] 메인 페이지에서 1인기능, 2인 기능 선택하도록 분기 처리
- [x] 1인 기능 선택시 운동 후 로직 구현
- [x] 1인 기능으로 운동 후 버디 진화뷰 구현

**Comment by bokoo14** [comment]
1인 기능 뷰의 구현은 모두 완료하였습니다.
하지만 iOS16버전의 업데이트로 인해, NavigationLink(isActive:destination:label:) 컴포넌트가 사라졌습니다.

오류 내용
'init(isActive:destination:label:)' was deprecated in iOS 16.0: use NavigationLink(value:label:), or navigationDestination(isPresented:destination:), inside a NavigationStack or NavigationSplitView

따라서 이로 인해 앱이 정상적으로 다음 네비게이션으로 이동하지 않는 오류가 발생합니다. 
확인 후, 전체적으로 Navigation기능을 수정하여야 합니다. 
참고: https://developer.apple.com/forums/thread/708398
위의 링크를 참고하여 수정해야 할것입니다.

**Comment by bokoo14** [comment]
1인 기능을 개발 후, test해보았습니다. 

1인기능, 2인기능 모두 navigation이 제대로 동작하지 않는 issue를 발견했습니다.
이를 해결하기 위해 다른 개발자들과의 소통이 필요하다고 생각이 듭니다.
다음 회의때 논의해보아야 할 것입니다.

**Comment by DhKimy** [comment]
> 1인 기능 뷰의 구현은 모두 완료하였습니다. 하지만 iOS16버전의 업데이트로 인해, `NavigationLink(isActive:destination:label:)` 컴포넌트가 사라졌습니다.
> 
> 오류 내용 `init(isActive:destination:label:)` was deprecated in iOS 16.0: use `NavigationLink(value:label:)`, or `navigationDestination(isPresented:destination:)`, inside a `NavigationStack` or `NavigationSplitView`
> 
> 전체적으로 Navigation기능을 수정하여야 합니다. 참고: https://developer.apple.com/forums/thread/708398 위의 링크를 참고하여 수정해야 할것입니다.

버그 수정 시 개선토록 하겠습니다.
